// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArw459kpAPLeMDt1MQuGOfQjFf8meOgPY',
    appId: '1:964573288964:web:aa9678fd82422fff197351',
    messagingSenderId: '964573288964',
    projectId: 'medfliqap',
    authDomain: 'medfliqap.firebaseapp.com',
    storageBucket: 'medfliqap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpxG3tAeLeqvOr2Cil2PTHg-9fUGR5mv4',
    appId: '1:964573288964:android:185c3c406d5b9d83197351',
    messagingSenderId: '964573288964',
    projectId: 'medfliqap',
    storageBucket: 'medfliqap.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuncVmXjJcNI4KCses5N7nCOuH1iUY6kI',
    appId: '1:964573288964:ios:bac4985c14120849197351',
    messagingSenderId: '964573288964',
    projectId: 'medfliqap',
    storageBucket: 'medfliqap.firebasestorage.app',
    iosBundleId: 'com.example.medfliq',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuncVmXjJcNI4KCses5N7nCOuH1iUY6kI',
    appId: '1:964573288964:ios:bac4985c14120849197351',
    messagingSenderId: '964573288964',
    projectId: 'medfliqap',
    storageBucket: 'medfliqap.firebasestorage.app',
    iosBundleId: 'com.example.medfliq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArw459kpAPLeMDt1MQuGOfQjFf8meOgPY',
    appId: '1:964573288964:web:e5f78cb6211063b4197351',
    messagingSenderId: '964573288964',
    projectId: 'medfliqap',
    authDomain: 'medfliqap.firebaseapp.com',
    storageBucket: 'medfliqap.firebasestorage.app',
  );
}
